services:
  - type: web
    name: Book Nest
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn book_nest.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true