# Generated by Django 6.0.3 on 2026-03-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_new_arrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('marked_price', models.PositiveIntegerField()),
            ],
        ),
    ]
