# Generated by Django 6.0.3 on 2026-04-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_best_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_type', models.CharField(choices=[('new_arrival', 'New Arrival'), ('best_seller', 'Best Seller')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('session_key', models.CharField(max_length=100)),
            ],
        ),
    ]
